### ISSUE TITLE
大佬，server端是怎么运行的

### ISSUE THREAD

**Issue by UncAnnyZ** [Hanxiaoniao/scrcpy#1]
我运行的时候，但是app的apk安装后却链接不了

**Comment by Han-Xiao-Dao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"UncAnnyZ"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午2:30
收件人:&nbsp;"Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
我运行的时候，但是app的apk安装后却链接不了
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




server端 是使用adb命令push到 连接的手机上(路径是 /data/local )&nbsp;

运行的时候 使用的也是adb命令启动的 (adb shell CLASSPATH=/data/local/tmp/classes.dex app_process / my.package.MainClass)

关于这个你可以看看 scrcpy他的开发者 这部分的代码 是用的人家的

https://github.com/Genymobile/scrcpy/blob/master/DEVELOP.md

**Comment by UncAnnyZ** [comment]
我英语不是很好，是指打包的jar push到/data/local/tmp 然后adb命令启动的 (adb shell CLASSPATH=/data/local/tmp/classes.dex app_process / my.package.MainClass)

类似：adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / my.package.MainClass

**Comment by Han-Xiao-Dao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"UncAnnyZ"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午3:15
收件人:&nbsp;"Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;;
抄送:&nbsp;"开发部-张东东"<2867979269@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
我英语不是很好，是指打包的jar push到/data/local/tmp 然后adb命令启动的 (adb shell CLASSPATH=/data/local/tmp/classes.dex app_process / my.package.MainClass)
 
类似：adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / my.package.MainClass
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.




对

**Comment by UncAnnyZ** [comment]
Aborted是什么情况呢

**Comment by Han-Xiao-Dao** [comment]
有图吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午3:38
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
Aborted是什么情况呢

**Comment by UncAnnyZ** [comment]
![image](https://user-images.githubusercontent.com/49876144/84004590-5b4e3380-a99e-11ea-826e-b38bbad90a42.png)
他这个手机本身就有scrcpy，但是我这里要弄成手机客户端去操作手机，有没有可能是之前的scrcpy影响了。

**Comment by Han-Xiao-Dao** [comment]
这个名字是错的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午3:41
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 

 他这个手机本身就有scrcpy，但是我这里要弄成手机客户端去操作手机，有没有可能是之前的scrcpy影响了。

**Comment by UncAnnyZ** [comment]
![image](https://user-images.githubusercontent.com/49876144/84005403-ac125c00-a99f-11ea-8337-836322b28180.png)

**Comment by Han-Xiao-Dao** [comment]
这是用我自己编译出来的jar运行的,他的原来那个需要传许多参数

直接运行是这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午3:50
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)

**Comment by UncAnnyZ** [comment]
我现在尝试一下你的，你那个server端怎么安装呢~麻烦大佬了，命令行是咋样的

**Comment by Han-Xiao-Dao** [comment]
我的那个不是一个成熟的工具,只写了一部分需要先使用android studio 打包 然后 跟那个一样 放到服务器上&nbsp;

编译完成在这里

然后这样&nbsp;&nbsp;

这就是运行起来的 会打印这句日志




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午4:30
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
我现在尝试一下你的，你那个server端怎么安装呢~麻烦大佬了，命令行是咋样的

**Comment by UncAnnyZ** [comment]
好像没有图片

**Comment by Han-Xiao-Dao** [comment]
??图片没传过去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午4:40
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
好像没有图片

**Comment by Han-Xiao-Dao** [comment]
第一步




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午4:40
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
好像没有图片

**Comment by Han-Xiao-Dao** [comment]
第三步







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午4:40
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
好像没有图片

**Comment by Han-Xiao-Dao** [comment]
第二步







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UncAnnyZ"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午4:40
收件人: "Han-Xiao-Dao/scrcpy"<scrcpy@noreply.github.com&gt;; 
抄送: "开发部-张东东"<2867979269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Han-Xiao-Dao/scrcpy] 大佬，server端是怎么运行的 (#1)





 
好像没有图片

**Comment by UncAnnyZ** [comment]
太惨了，我这里没有显示图片
![image](https://user-images.githubusercontent.com/49876144/84011100-378feb00-a9a8-11ea-87a7-eb354b64b442.png)
